<%@ Page Title="<%$ Resources:Site, title_marque %>" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="Marque.aspx.cs" Inherits="TP_Session___CHIM.Marque" UICulture="auto" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="cp1" runat="server">

    <asp:SqlDataSource 
        ID="SqlDtBiere" 
        runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        SelectCommand="SELECT * FROM [Marque]"
        UpdateCommand="UPDATE [Marque] SET Marque=@Marque, Brasseur=@Brasseur, Pourcentage=@Pourcentage WHERE ID = @ID"
        DeleteCommand="DELETE [Marque] WHERE ID= @ID">
    </asp:SqlDataSource>

    <div class="ajout">

        <asp:Label
            ID="lb_add"
            runat="server"
            Text="<%$ Resources:Site, add %>"
            Font-Bold="true">
        </asp:Label>

        <br /><br />

        <asp:Label
            ID="lb_add_nom"
            runat="server"
            AssociatedControlID="tb_addnom"
            Text="<%$ Resources:Site, lb_nomb %>">
        </asp:Label>

        <asp:TextBox
            ID="tb_addnom"
            runat="server">
        </asp:TextBox>

        <br />

        <asp:Label
            ID="lb_brasseur"
            runat="server"
            AssociatedControlID="tb_brasseur"
            Text="<%$ Resources:Site, lb_brasseur %>">
        </asp:Label>

        <asp:TextBox
            ID="tb_brasseur"
            runat="server">
        </asp:TextBox>

        <br />

        <asp:Label
            ID="lb_pourcentage"
            runat="server"
            AssociatedControlID="tb_pour"
            Text="<%$ Resources:Site, lb_pour %>">
        </asp:Label>

        <asp:TextBox
            ID="tb_pour"
            runat="server">
        </asp:TextBox>

        <br /><br />

        <asp:Button
            ID="bt_add"
            runat="server"
            Text="<%$ Resources:Site, bt_add %>"
            OnClick="bt_add_Click" />
    </div>

    <div class="dgv">

        <br /><br /><br /><br />

        <asp:GridView
            ID="gv"
            runat="server" 
            AutoGenerateColumns="False" 
            DataKeyNames="ID" 
            DataSourceID="SqlDtBiere"
            AutoGenerateEditButton="true"
            AutoGenerateDeleteButton="true"
            AllowPaging="true" 
            PageSize="3" 
            
            PagerStyle-CssClass="pgStyle"
            AlternatingRowStyle-CssClass="gvAltRow"
            RowStyle-CssClass="rowStyle"
            HeaderStyle-CssClass="gvHeader">

            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="Marque" HeaderText="Marque" SortExpression="Marque" />
                <asp:BoundField DataField="Brasseur" HeaderText="Brasseur" SortExpression="Brasseur" />
                <asp:BoundField DataField="Pourcentage" HeaderText="Pourcentage" SortExpression="Pourcentage" />
            </Columns>
        </asp:GridView>
    </div>

</asp:Content>
