//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une bière.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        internal static string bt_add {
            get {
                return ResourceManager.GetString("bt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à images/boutons/brosse.png.
        /// </summary>
        internal static string bt_brosse {
            get {
                return ResourceManager.GetString("bt_brosse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer.
        /// </summary>
        internal static string bt_date {
            get {
                return ResourceManager.GetString("bt_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à images/boutons/histoire.png.
        /// </summary>
        internal static string bt_histoire {
            get {
                return ResourceManager.GetString("bt_histoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à images/boutons/marque.png.
        /// </summary>
        internal static string bt_marque {
            get {
                return ResourceManager.GetString("bt_marque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à images/boutons/quand.png.
        /// </summary>
        internal static string bt_quand {
            get {
                return ResourceManager.GetString("bt_quand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string connexion {
            get {
                return ResourceManager.GetString("connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département d&apos;informatique.
        /// </summary>
        internal static string Depart {
            get {
                return ResourceManager.GetString("Depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;histoire de la bière !.
        /// </summary>
        internal static string H_histoire {
            get {
                return ResourceManager.GetString("H_histoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à images/50 francais.jpg.
        /// </summary>
        internal static string imgLink1 {
            get {
                return ResourceManager.GetString("imgLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à images/histoire bière.jpg.
        /// </summary>
        internal static string img_nav {
            get {
                return ResourceManager.GetString("img_nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brasseur : .
        /// </summary>
        internal static string lb_brasseur {
            get {
                return ResourceManager.GetString("lb_brasseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici la date de votre prochaine brosse : .
        /// </summary>
        internal static string lb_date_choisie {
            get {
                return ResourceManager.GetString("lb_date_choisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choissisez une date pour votre prochaine brosse : .
        /// </summary>
        internal static string lb_intruc {
            get {
                return ResourceManager.GetString("lb_intruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marque : .
        /// </summary>
        internal static string lb_nomb {
            get {
                return ResourceManager.GetString("lb_nomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pourcentage : .
        /// </summary>
        internal static string lb_pour {
            get {
                return ResourceManager.GetString("lb_pour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quand on aime la bière....
        /// </summary>
        internal static string lb_titre_acceuil {
            get {
                return ResourceManager.GetString("lb_titre_acceuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse courriel : .
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom : .
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Histoire.
        /// </summary>
        internal static string title_histoire {
            get {
                return ResourceManager.GetString("title_histoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La bière - Acceuil.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matériel d&apos;ivresse.
        /// </summary>
        internal static string title_ivresse {
            get {
                return ResourceManager.GetString("title_ivresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marques.
        /// </summary>
        internal static string title_marque {
            get {
                return ResourceManager.GetString("title_marque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quand.
        /// </summary>
        internal static string title_quand {
            get {
                return ResourceManager.GetString("title_quand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La bière est une boisson alcoolisée obtenue par fermentation d&apos;un moût préparé à partir de matières premières amylacées (orge, maïs, riz, banane, manioc) et d&apos;eau potable. Le moût est un jus sucré obtenu à l&apos;issue d&apos;une étape importante de la fabrication de la bière, le brassage, terme à l&apos;origine des vocables brasseur et brasserie..
        /// </summary>
        internal static string txt1 {
            get {
                return ResourceManager.GetString("txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus spécifiquement de nos jours, elle est généralement produite à partir d’eau, de malt (céréale germée, principalement de l&apos;orge, parfois additionné d&apos;autres céréales) et depuis le Moyen Âge, de houblon qui apporte le parfum et l&apos;amertume nécessaires à chaque bière, et agit comme conservateur naturel..
        /// </summary>
        internal static string txt2 {
            get {
                return ResourceManager.GetString("txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elle est consommée à la pression, en bouteille et en canette. Symbole associé à la fête, à la convivialité en famille ou entre amis, elle est à l&apos;origine de nombreux évènements festifs (fête de la bière, mondial de la bière, journée internationale de la bière) mais suscite également de nombreux excès (jeux à boire tels que le bière-pong, le Flip cup (en), le bong à bière (en), la botte de bière (de) ou le barathon)..
        /// </summary>
        internal static string txt3 {
            get {
                return ResourceManager.GetString("txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Des versions très faiblement alcoolisées (variant de 2° à 0°) sont présentes sur le marché. Contrairement aux autres boissons « sans alcool », elles sont élaborées par les mêmes procédés que la bière classique. La fabrication de la bière est réalisée industriellement ou artisanalement dans une brasserie mais est réalisable par le particulier..
        /// </summary>
        internal static string txt4 {
            get {
                return ResourceManager.GetString("txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La bière est la plus ancienne boisson alcoolisée connue au monde et la boisson la plus consommée après l&apos;eau et le thé..
        /// </summary>
        internal static string txt5 {
            get {
                return ResourceManager.GetString("txt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;histoire de la bière est intimement liée à celle de ses ingrédients, ainsi qu&apos;aux avancées technologiques qui firent de cette boisson le breuvage que l&apos;on connaît aujourd’hui. Les premières cultures de céréales, notamment de l&apos;orge et de l&apos;épeautre (une variété de blé), ont été attestées en 8000 av. J.-C. en Mésopotamie. Tous les ingrédients étant disponibles dès cette époque, la bière pouvait donc exister et l&apos;on estime son invention/découverte à 6000 av. J.-C. Cependant, les preuves formelles de son exi [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string txt6 {
            get {
                return ResourceManager.GetString("txt6", resourceCulture);
            }
        }
    }
}
